
name: memory_game
description: An advanced memory game with multiple modes and features
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  audioplayers: ^5.0.0
  google_fonts: ^5.0.0
  path_provider: ^2.1.5
  flutter_staggered_animations: ^1.1.0
  confetti: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.2


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mini-smemory.png"
  transparent: false
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/